### ISSUE TITLE
Transparent weapon sides

### ISSUE THREAD

**Issue by MartyParty21** [TheValarProject/AwakenDreamsClient#29]
Most of higher quality textured weapons has semi-transparent border pixels, which causes both player facing and front facing (blade edge) sides being transparent. 
Can be easilly fixed by editing the texture to have untransparent borders, but its a longer job.

**Comment by scribblemaniac** [comment]
Yes I noticed this as well (it is also on my private todo list), even some blocks suffer from this issue. I should be able to use imagemagick to automate the texture correction. After browsing the documentation, I think something like this should work:
```
mogrify -channel A -threshold 50% *.png
```

**Comment by scribblemaniac** [comment]
Issue completion checklist:
- [X] Remove translucent pixels from items
- [x] Remove translucent pixels from blocks
- [x] Build a test script to catch this in the future

**Comment by scribblemaniac** [comment]
This should be solved now, closing 😁
